server:
  port: 8084


spring:
  application:
    name: user-service

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**


#  - Path=/** --for entire URL

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
    discovery:
      enabled: true


#  server will be register here


eureka:
    instance:
      prefer-ip-address: true


    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

# spring security configuration for api gateway


okta:
  oauth2:
    issuer: https://dev-13071527.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaotjgsajidiL2YT5d7
    client-secret: GNSxqZYhg8TUSInifQwZabLzXwTHg3KaMr1mihqrJTb0YPAToqPA1wYVP3McQfQ0
    scopes: openid, email , profile , offline_access

