spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: Rating-Service

server:
  port: 8083

#    server will be register here
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#      octa security for rating service

okta:
  oauth2:
    issuer: https://dev-13071527.okta.com/oauth2/default
    audience: api://default


